### ISSUE TITLE
Can not clone repository

### ISSUE THREAD

**Issue by tooh** [JolleJolles/pirecorder#18]
git clone --depth 1 http://git.videolan.org/git/x264
Cloning into 'x264'...
fatal: repository 'http://git.videolan.org/git/x264/' not found

**Comment by JolleJolles** [comment]
Where did you run into this issue? What where you trying to do?

**Comment by tooh** [comment]
Was trying to install ffmpeg on my Raspberry Pi according to your instructions.

Seems repository is moved to another location.

**Comment by patrickpissurno** [comment]
Hi,

They moved [their repos to GitLab](https://git.videolan.org/).

New URL: https://code.videolan.org/videolan/x264.git
