### ISSUE TITLE
Debian Bullseye, no more picamera

### ISSUE THREAD

**Issue by roaldarbol** [JolleJolles/pirecorder#30]
Just read that with their newest release of Raspberry Pi OS built on Debian Bullseye, RP will no longer support raspicam or picamera. It should have no immediate effect, but probably means that pirecorder won't work on the new OS and that it will have to have a new branch for this. They're currently working on a new Python interface, picamera2, so I imagine that could be the backbone of a new branch.

https://www.raspberrypi.com/news/bullseye-camera-system/

**Comment by JolleJolles** [comment]
Thanks as well for your message here. I just left a note on the readme (28531828269b814b30eef8fef6b4b70cd09b8d8f). Cheers!
