### ISSUE TITLE
Troubles Using v1 Camera (Rev. 1.3)

### ISSUE THREAD

**Issue by stever2022** [JolleJolles/pirecorder#34]
Hi!

I have been having problems using _pirecorder_ with an older version of the Pi camera, v1 5MP, aka _Raspberry Pi Camera Rev 1.3_. There are issues handling the resolution of this camera, as explained below, and this is critical for _pirecorder_ to be usable with this camera. I have found some probable causes, and I have shared them here, hoping to resolve the troubles through dialogue and colaboration. I like the idea of pirecorder and I want it to work, so please understand that I have only best wishes for its success.

My system consists of: 
- Raspberry Pi 3 Model B v1.2
- Raspberry Pi OS, 32-bit version, Bullseye, updated
- legacy camera interface enabled
- Python 3.9
- pirecorder v3.3.0, installed via _sudo pip3 install pirecorder==3.3.0_
- Raspberry Pi Camera Rev 1.3, OV5647, maximum still resolution 2592 x 1944 pixels, maximum video 1080p
- one humble old programmer, a professional engineer, experienced and learning, but not an expert in Python or Linux

I have been manually working through the features of pirecorder, using the notebook _Using PiRecorder_ as a guide [link](https://github.com/JolleJolles/pirecorder/blob/master/notebooks/running-PiRecorder.ipynb). Things progressed well until, after drawing a rectangular area on the interactive live video stream, I used the zoom key (z-key). At that point the program crashes, where picamera raises an exception due to an invalid resolution, specifically, height of 1952, where 1944 is the hardware maximum.

         Traceback (most recent call last):
          File "/home/pi/picamera-projects/test1-pirecorder.py", line 10, in <module>
            rec.stream()
          File "/home/pi/.local/lib/python3.9/site-packages/pirecorder/pirecorder.py", line 520, in stream
            vidstream = Stream(internal=True, rotation=self.config.cus.rotation,
          File "/home/pi/.local/lib/python3.9/site-packages/pirecorder/stream.py", line 119, in __init__
            self.drawer()
          File "/home/pi/.local/lib/python3.9/site-packages/pirecorder/stream.py", line 213, in drawer
            zimg = self.vid2.img()
          File "/home/pi/.local/lib/python3.9/site-packages/pirecorder/videoin.py", line 112, in img
            self.camera.resolution = self.maxres
          File "/usr/lib/python3/dist-packages/picamera/camera.py", line 2270, in _set_resolution
            raise PiCameraValueError(
        picamera.exc.PiCameraValueError: Invalid resolution requested: PiResolution(width=2592, height=1952)

I tried to circumvent this error by setting _maxres = (2592, 1944)_ in the pirecorder.conf configuration file.  The results were no different; the program crashed with the same error.

I browsed the _stream.py_ and _videoin.py_ source code for clues:

1. In _videoin.py_, the _self.maxres_ values were set at lines 47 to 54. The objectionable resolution arises from the final condition 'else:'. So, the tests of _maxres_ must have determined: it is not a tuple, it is not "v2", and it is not "hq".

            if isinstance(maxres, tuple):
                  self.maxres = maxres
            elif maxres == "v2":
                   self.maxres = (3264,2464)
            elif maxres == "hq":
                  self.maxres = (4056,3040)
            else:
                  self.maxres = (2592,1952)

2. I tried to override this issue by explicitly setting maxres = (2592, 1944), a tuple as it should be, using _rec.settings(maxres = (2592, 1944))_.  This worked as far as getting the correct text into the _pirecorder.conf_ file:

        [rec]
        recdir = pirecorder/recordings
        subdirs = False
        label = test
        rectype = img
        maxres = (2592, 1944)

3. However, on re-running rec.stream(), I got the same fatal error as above,   _picamera.exc.PiCameraValueError: Invalid resolution requested: PiResolution(width=2592, height=1952)_.

4. It was difficult to understand why the correct resolution was not used, after setting the configuration explicitly.  Following the error propagation up to _pirecorder.py_ revealed some possibilities, where the configuration file is read at line 115 using LocalConfig():

        from localconfig import LocalConfig
        ...
        self.config = LocalConfig(self.configfile, compact_form = True)
        
5. The module _localconfig_ does not work with **tuple** type of variables, and as far as I can tell, when it encounters text that looks like a tuple, it treats them as strings, i.e., it delivers a string type variable when a tuple-like element is read.  The variable types handled are listed in the readme.rst at [link](https://github.com/maxzheng/localconfig#supported-data-types). These brief tests validate the handling of tuple-like elements types as strings, and that elements read from the config file will always fail a test for tuple:

        import pirecorder
        rec = pirecorder.PiRecorder()
        rec.settings(maxres = (2592, 1944))
        print(rec.config.rec.maxres)                           # output: (2592, 1944)
        print(isinstance(rec.config.rec.maxres, tuple))        # output: False
        maxres = rec.config.rec.maxres
        print(isinstance(maxres, tuple))                       # output: False
        print(type(maxres))                                    # output: <class 'str'>
        print(type(rec.config.rec.maxres))                     # output: <class 'str'>
        print(isinstance((2592, 1944), tuple))                 # output: True
        print(type(rec.config.cus.roi))                        # output: <class 'str'>
        print(type(rec.config.cus.gains))                      # output: <class 'str'>
        print(type(rec.config.img.imgdims))                    # output: <class 'str'>
        print(type(rec.config.vid.viddims))                    # output: <class 'str'>

6. Converting strings from the config file that should be tuples into tuples seems potentially quite messy.  One solution found [here](https://stackoverflow.com/questions/15197673/using-pythons-eval-vs-ast-literal-eval) is to use ast.literal_eval(), to convert the tuple-like string into a 'real' tuple.  However, this appears to fail badly if the string is actually a string, e.g. "v2" or "hq", so it is not bullet-proof.

        import ast
        ...
        print(ast.literal_eval(rec.config.rec.maxres))                       # output: (2592, 1944)
        print(isinstance(ast.literal_eval(rec.config.rec.maxres), tuple))    # output: True

**In conclusion**, there appears to be a problem with the default resolution for the Pi v1 camera, hardcoded into videoin.py.  There seems to be another problem, that the configuration file elements that should be tuples are not read as tuples, and in the case of resolution in videoin.y, that causes the default resolution to be used, instead of an explicit value from the config file as intended. There may be solutions that allow the use of tuples for the dimensions, but a solution for maxres that can handle both a tuple-like string and strings such as "v2" and "hq" has not been found yet.  An alternative would be to create separate, simple int/float configuration elements for cases where tuples were used: maxres, roi, gains, imgdims, viddims.  I can't get past the resolution problem yet, to see what happens when these other parameters are encountered, but I am expecting more troubles with the same causes.

For **follow-up action**, I would appreciate it if you would verify my findings and provide some directions for resolution. If I have erred or misused the package somehow, I need to know that and how to make corrections. If the program needs some revision, I hope that it will not be too onerus for you to make them. I will stand by to aid if I can, and as you request; I will certainly try out any revisions to validate them with my cameras and report back.

Sincerely,
Steve

**Comment by JolleJolles** [comment]
Dear Steve,

Apologies for the late reply! I had somehow not received a notification and therefore only discovered this raised issue now while solving another issue that was raised yesterday.

Thanks for spotting these two minor issues. Indeed the max resolution setting for cameras < v2 was wrong as being (2592,1944) and tuples were not correctly identified. Both of this has now been fixed in [v3.3.4](https://github.com/JolleJolles/pirecorder/releases/tag/v3.3.4). Please let me know if you have any further issues.

Thanks,

Jolle
